# Generated by Django 6.1.1 on 2026-10-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('docente', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('durata', models.PositiveIntegerField(help_text='Durata in ore')),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('in_corso', 'In corso'), ('concluso', 'Concluso'), ('annullato', 'Annullato')], default='programmato', max_length=20)),
                ('posti_massimi', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'corso',
                'verbose_name_plural': 'corsi',
                'ordering': ['data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='corsi.corso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'iscrizione',
                'verbose_name_plural': 'iscrizioni',
                'ordering': ['-data_iscrizione'],
                'constraints': [models.UniqueConstraint(fields=('utente', 'corso'), name='iscrizione_unica')],
            },
        ),
    ]
